# Generated by Django 2.2.17 on 2021-07-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20210209_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='intro',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
